blueprints/auth.py
from flask import Blueprint, flash, render_template, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user, LoginManager
from forms import LoginForm, RegisterForm
from werkzeug.security import check_password_hash, generate_password_hash

from database_config import db
from models import User

login_manager = LoginManager()

auth = Blueprint("auth", __name__)
@auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            return redirect(url_for('index'))
        flash('Invalid username or password', 'danger')
    return render_template('login.html', form=form)


@auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():

        if User.query.filter_by(username=form.username.data).first():
            flash('username already taken', 'danger')
            return render_template('register.html', form=form)
        
        if User.query.filter_by(username=form.email.data).first():
            flash('email already taken', 'danger')
            return render_template('register.html', form=form)
        
        hashed_password = generate_password_hash(form.password.data, method='pbkdf2')
        
        if form.role.data == "Admin" and current_user.role == "admin":
            role = "admin"
        else:
            role = "pax"
             
        new_user = User(name = form.name.data, surname = form.surname.data, username=form.username.data, email=form.email.data, password=hashed_password, numberOfId = form.numberOfId.data ,role=role)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('auth.login'))
    return render_template('register.html', form=form, current_user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@login_manager.user_loader
def load_user(user_id):
   return User.query.get(int(user_id))

blueprints/reservation.py
from flask import Blueprint, flash, render_template, redirect, url_for, request
from flask_login import login_user, login_required, logout_user, current_user, LoginManager
from forms import LoginForm, RegisterForm, SearchForm, ReservationForm1, ReservationForm2
from werkzeug.security import check_password_hash, generate_password_hash
from scraping import is_reservation_possible, get_iata_code, airlines_details, airline_code, get_airport_name_by_iata
from datetime import datetime
from sqlalchemy import func

from database_config import db
from models import User, Reservation, CreateSeats, Flight

reservation = Blueprint("reservation", __name__)

@reservation.route('/', methods=['GET', 'POST'])
def search():
    form = SearchForm()
    if request.method == 'GET':
        return render_template('index.html', form=form, current_user=current_user, len=len, get_iata_code=get_iata_code, list=list)
    
    if request.method == 'POST' and form.validate_on_submit():
        base_code = get_iata_code(form.base_.data)
        to_code = get_iata_code(form.to.data)
        time_of_departure = form.departure.data
        return_departure = form.return_departure.data
        back = form.back.data

        if not base_code and to_code: # no airports found
            flash("Sorry, we are not flying from/to this airport. Please insert another one.")
            return redirect(url_for('reservation.search'))

        if not (len(base_code) == 1 and len(to_code) == 1): # more than one
            return render_template('index.html', form=form, current_user=current_user, base_airports=base_code, to_airports=to_code, len=len, get_iata_code=get_iata_code, list=list)

        
        base_code = list(base_code.values())[0]
        to_code = list(to_code.values())[0]

        if not is_reservation_possible(base_code, to_code):
            flash("Sorry, there are seats on flights between those airports")
            return False
        
        airlines = airlines_details(base_code, to_code)


        if airlines == None:
            flash("Sorry. We don't fly that direction")
            return render_template('index.html', form=form, current_user=current_user, len=len, get_iata_code=get_iata_code, list=list)
        
        return render_template('select_airline.html', 
                                airlines=airlines,
                                base_code=base_code,
                                to_code=to_code, 
                                fromAirport=form.base_.data, 
                                destinationAirport=form.to.data, 
                                current_user=current_user, 
                                airline_code=airline_code,  
                                departure=time_of_departure, 
                                return_departure=return_departure,
                                back=back)

        
        
    #flash("Wrong input data!")
    return redirect(url_for('reservation.search'))

@reservation.route('/select_airline/<string:base_code>/<string:to_code>/<string:airline_code>/<string:fromAirport>/<string:destinationAirport>/<path:departure>/<path:return_departure>/<string:back>', methods=['GET'])
def select_airline(airline_code, base_code, to_code, fromAirport, destinationAirport, departure, return_departure, back):
    return redirect(url_for('reservation.make_reservation',
                            fromAirport=fromAirport,
                            destinationAirport=destinationAirport, 
                            fromCode=base_code, 
                            destinationCode=to_code,
                            airlineCode=airline_code, 
                            departure=departure, 
                            return_departure=return_departure,
                            back=back))

@reservation.route('/reservation/via', methods=['GET', 'POST'])
def make_reservation_via():
    via = request.args.get('via')
    return render_template('via.html', via=via)

@reservation.route('/reservation/data', methods=['GET', 'POST'])
@login_required
def make_reservation():
    form = ReservationForm1()
    fromCode = request.args.get('fromCode')
    destinationCode = request.args.get('destinationCode')
    airline_code = request.args.get('airlineCode')
    departure = request.args.get('departure')
    return_departure = request.args.get('return_departure')
    back = request.args.get('back')
    try:
        departure = datetime.strptime(departure, "%Y-%m-%d %H:%M:%S")
    except:
        departure = datetime.strptime(departure, "%Y-%m-%d")

    if request.method == 'GET':
        return render_template('reservation_data.html', form=form, current_user=current_user)
    if request.method == 'POST' and form.validate_on_submit():
        fromAirport = request.args.get('fromAirport')
        destinationAirport = request.args.get('destinationAirport')
        seats = CreateSeats()
        flight = Flight.query.filter_by(fromCode=fromCode, destinationCode=destinationCode, airlineCode=airline_code).first()
        if not flight:
            return render_template('seats.html', 
                                   seats=seats,
                                   taken_seats=[],  # Brak zarezerwowanych miejsc dla nowego lotu
                                   fromAirport=fromAirport,
                                   destinationAirport=destinationAirport, 
                                   fromCode=fromCode, 
                                   destinationCode=destinationCode,
                                   airlineCode=airline_code, 
                                   departure=departure, 
                                   return_departure=return_departure,
                                   back=back)
        else:
            taken_seats = flight.taken_seats.split(',') if flight.taken_seats else []
            return render_template('seats.html', 
                                   seats=seats,
                                   taken_seats=taken_seats,
                                   fromAirport=fromAirport,
                                   destinationAirport=destinationAirport, 
                                   fromCode=fromCode, 
                                   destinationCode=destinationCode,
                                   airlineCode=airline_code, 
                                   departure=departure, 
                                   return_departure=return_departure,
                                   back=back)

@reservation.route('/reservation/seat-<string:seat>', methods=['GET', 'POST'])
def make_reservation2(seat):
    fromAirport = request.args.get('fromAirport')
    destinationAirport = request.args.get('destinationAirport')
    fromCode = request.args.get('fromCode')
    destinationCode = request.args.get('destinationCode')
    airline_code = request.args.get('airlineCode')
    departure = request.args.get('departure')
    return_departure = request.args.get('return_departure')
    back = request.args.get('back')

    flight = Flight.query.filter_by(fromCode=fromCode, destinationCode=destinationCode, airlineCode=airline_code).filter(Flight.timeOfDeparture == departure).first()
    if not flight:
        return redirect(url_for('reservation.confirm_reservation',
                                fromAirport=fromAirport,
                                destinationAirport=destinationAirport, 
                                fromCode=fromCode, 
                                destinationCode=destinationCode,
                                seat=seat, 
                                airline_code=airline_code, 
                                departure=departure, 
                                return_departure=return_departure,
                                back=back))
    else:
        taken_seats = flight.taken_seats.split(',') if flight.taken_seats else []
        print(taken_seats)
        if seat in taken_seats:
            seats = CreateSeats()
            return render_template('seats.html', 
                                   seats=seats,
                                   taken_seats=taken_seats,
                                   fromAirport=fromAirport,
                                   destinationAirport=destinationAirport, 
                                   fromCode=fromCode, 
                                   destinationCode=destinationCode,
                                   airlineCode=airline_code, 
                                   departure=departure, 
                                   return_departure=return_departure,
                                   back=back)
        else:
            return redirect(url_for('reservation.confirm_reservation',
                                    fromAirport=fromAirport,
                                    destinationAirport=destinationAirport, 
                                    fromCode=fromCode, 
                                    destinationCode=destinationCode,
                                    seat=seat, 
                                    airline_code=airline_code, 
                                    departure=departure, 
                                    return_departure=return_departure,
                                    back=back))

@reservation.route('/reservation/confirm', methods=['GET', 'POST'])
@login_required
def confirm_reservation():
    form = ReservationForm2()
    fromCode = request.args.get('fromCode')
    destinationCode = request.args.get('destinationCode')
    fromAirport = get_airport_name_by_iata(fromCode)
    destinationAirport = get_airport_name_by_iata(destinationCode)
    airline_code = request.args.get('airline_code')
    seat = request.args.get('seat')
    departure_str = request.args.get('departure')
    return_departure = request.args.get('return_departure')
    back = request.args.get('back')
    max_flight_id = db.session.query(func.max(Flight.id)).scalar()
    if not max_flight_id:
        max_flight_id = 0
    

    try:

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    {% block styles %}
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"> 
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
        <script type="text/javascript">
        $(document).ready(function(){
            $(".nav-item.dropdown").mouseenter(function() {
                $(this).find(".dropdown-menu").show(300);
                });

            $(".nav-item.dropdown").mouseleave(function() {
            $(this).find(".dropdown-menu").hide(300);     
            });
        });
    </script>
{% endblock %}
</head>
<body>
    

{% block navbar %}
<nav class="navbar navbar-expand-lg bg-info">
    <div class="container-fluid">
        <div class="navbar-brand d-flex align-items-center">
            <div id="logo" class="mx-1">
                <svg xmlns="http://www.w3.org/2000/svg" width="40" height="40" fill="currentColor" class="bi bi-airplane-engines" viewBox="0 0 16 16">
                    <path d="M8 0c-.787 0-1.292.592-1.572 1.151A4.35 4.35 0 0 0 6 3v3.691l-2 1V7.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.191l-1.17.585A1.5 1.5 0 0 0 0 10.618V12a.5.5 0 0 0 .582.493l1.631-.272.313.937a.5.5 0 0 0 .948 0l.405-1.214 2.21-.369.375 2.253-1.318 1.318A.5.5 0 0 0 5.5 16h5a.5.5 0 0 0 .354-.854l-1.318-1.318.375-2.253 2.21.369.405 1.214a.5.5 0 0 0 .948 0l.313-.937 1.63.272A.5.5 0 0 0 16 12v-1.382a1.5 1.5 0 0 0-.83-1.342L14 8.691V7.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v.191l-2-1V3c0-.568-.14-1.271-.428-1.849C9.292.591 8.787 0 8 0M7 3c0-.432.11-.979.322-1.401C7.542 1.159 7.787 1 8 1s.458.158.678.599C8.889 2.02 9 2.569 9 3v4a.5.5 0 0 0 .276.447l5.448 2.724a.5.5 0 0 1 .276.447v.792l-5.418-.903a.5.5 0 0 0-.575.41l-.5 3a.5.5 0 0 0 .14.437l.646.646H6.707l.647-.646a.5.5 0 0 0 .14-.436l-.5-3a.5.5 0 0 0-.576-.411L1 11.41v-.792a.5.5 0 0 1 .276-.447l5.448-2.724A.5.5 0 0 0 7 7z"/>
                </svg>
            </div>
            <span class="navbar-text ms-1 fw-bold fs-1" style="color: black;">FlightBooking</span>
        </div>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="{{ url_for('index') }}" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Home
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{{ url_for('index') }}#search-flight">Search Flight</a>
                        <a class="dropdown-item" href="{{ url_for('index') }}#inspiration">Get Inspired</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('fleet') }}">Our Fleet</a> <!--zmieniłem adres bo póki nie ma ma tych templatów to strona nie działa -->
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('baggage') }}">Baggage</a> <!--zmieniłem adres bo póki nie ma ma tych templatów to strona nie działa -->
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('pets') }}">Travel with Pets</a> <!--zmieniłem adres bo póki nie ma ma tych templatów to strona nie działa -->
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('meals') }}">Meals & Drinks</a> <!--zmieniłem adres bo póki nie ma ma tych templatów to strona nie działa -->
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('contact') }}">Contact</a> <!--zmieniłem adres bo póki nie ma ma tych templatów to strona nie działa -->
                </li>
            </ul>
            <div class="d-flex justify-content-end">
                <ul class="navbar-nav">
                    {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a href="{{ url_for('reservation.my_reservations') }}"><button type="button" class="btn btn-light btn-lg">My reservations</button></a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.logout') }}"><button type="button" class="btn btn-light btn-lg">Logout</button></a>
                    </li>
                    {% else %}
                    <li class="nav-item me-2">
                        <a href="{{ url_for('auth.register') }}"><button type="button" class="btn btn-light btn-lg">Register</button></a>
                    </li>
                    <li class="nav-item">
                        <a href="{{ url_for('auth.login') }}"><button type="button" class="btn btn-light btn-lg">Login</button></a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</nav>
{% endblock %}


{% block content %}
<div class="container-fluid">
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        <div class="alert alert-info" role="alert">
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">{{ message }}</div>
            {% endfor %}
        </div>
        {% endif %}
    {% endwith %}
</div>
{% block main %}{% endblock %}

{% block footer %}
<div class="container-fluid">
    <div class="footer d-flex flex-column align-items-center" style="padding: 0;">
        <p class="mt-2 mb-2">© 2024 Flight Booking. All rights reserved.</p>
        <p class="mb-2">
            <a href="#">Privacy Policy</a> |
            <a href="#">Terms of Service</a>
        </p>
        <p class="mb-2">
            Follow us:
            <a href="https://facebook.com">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-facebook" viewBox="0 0 16 16">
                    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951"/>
                  </svg>
            </a> |
            <a href="https://twitter.com">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-twitter-x" viewBox="0 0 16 16">
                    <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"/>
                  </svg>
            </a> |
            <a href="https://instagram.com">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-instagram" viewBox="0 0 16 16">
                    <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.9 3.9 0 0 0-1.417.923A3.9 3.9 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.9 3.9 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.9 3.9 0 0 0-.923-1.417A3.9 3.9 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599s.453.546.598.92c.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.5 2.5 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.5 2.5 0 0 1-.92-.598 2.5 2.5 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233s.008-2.388.046-3.231c.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92s.546-.453.92-.598c.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92m-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217m0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334"/>
                  </svg>
            </a>
        </p>
    </div>

</div>
{% endblock %}

{% endblock %}
</body>
</html>

templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block main %}
<div class="airplane-container position-relative">
  <div class="airplane">
    <svg id="animated-plane" xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="currentColor" class="bi bi-airplane-engines-fill" viewBox="0 0 16 16">
      <path d="M8 0c-.787 0-1.292.592-1.572 1.151A4.35 4.35 0 0 0 6 3v3.691l-2 1V7.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.191l-1.17.585A1.5 1.5 0 0 0 0 10.618V12a.5.5 0 0 0 .582.493l1.631-.272.313.937a.5.5 0 0 0 .948 0l.405-1.214 2.21-.369.375 2.253-1.318 1.318A.5.5 0 0 0 5.5 16h5a.5.5 0 0 0 .354-.854l-1.318-1.318.375-2.253 2.21.369.405 1.214a.5.5 0 0 0 .948 0l.313-.937 1.63.272A.5.5 0 0 0 16 12v-1.382a1.5 1.5 0 0 0-.83-1.342L14 8.691V7.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v.191l-2-1V3c0-.568-.14-1.271-.428-1.849C9.292.591 8.787 0 8 0"/>
    </svg>
  </div>
  <div id="welcome-message" class="welcome-message d-none">We are happy to see you again!</div>
</div>

<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="login-container">
        <h2 class="login-heading">Login</h2>
        <form method="POST" action="{{ url_for('auth.login') }}">
          {{ form.hidden_tag() }}
          <div class="mb-3">
            {{ form.username.label }}
            {{ form.username(size=32, class="form-control") }}
          </div>
          <div class="mb-3">
            {{ form.password.label }}
            {{ form.password(size=32, class="form-control") }}
          </div>
          <div class="mb-3 form-check">
            {{ form.remember(class="form-check-input") }}
            {{ form.remember.label(class="form-check-label") }}
          </div>
          <div class="mb-3">
            {{ form.submit(class="btn btn-primary btn-lg") }}
          </div>
          <div class="text-center">
            <a href="{{ url_for('auth.register') }}" style="font-size: 13px;">Don't have account? Register here</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    document.getElementById('animated-plane').classList.remove('d-none');
    document.getElementById('animated-plane').addEventListener('animationend', function() {
      document.getElementById('welcome-message').classList.remove('d-none');
    });
  });
</script>
{% endblock %}


templates/reservation2.html
{% extends "base.html" %}
{% block title %}Making reservation{% endblock %}
{% block content %}
<div class="container">
  <div class="card text-center">
    <div class="card-header">
      <ul class="nav nav-pills card-header-pills">
        <li class="nav-item">
          <p class="nav-link disabled" >Step 1</p>
        </li>
        <li class="nav-item">
          <p class="nav-link disabled">Step 2</p>
        </li>
        <li class="nav-item">
          <p class="nav-link disabled">Step 3</p>
        </li>
        <li class="nav-item">
            <p class="nav-link active">Step 4</p>
        </li>
      </ul>
    </div>
  </div>
  <div class="reservation2">
  <div class="form-content">
  <h2 class="my-4 text-center">Making reservation</h2>
  <form method="POST" action="">
    {{ form.hidden_tag() }}
    <div class="form-group">
        <label for="luggage">{{ form.luggage.label }}</label><br>
        {{ form.luggage(class="form-control", size=32) }}<br>
    </div>
    <div class="form-group">
        <label for="insurance">{{ form.insurance.label }}</label><br>
        {{ form.insurance(class="form-control", size=32) }}<br>
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary w-100") }}
    </div></div></form></div>
{% endblock %}

templates/select_airline.html
{% extends "base.html" %}

{% block title %}
Select Airline
{% endblock %}

{% block main %}
<div class="container">
    <div class="card text-center">
        <div class="card-header">
          <ul class="nav nav-pills card-header-pills">
            <li class="nav-item">
              <p class="nav-link active" >Step 1</p>
            </li>
            <li class="nav-item">
              <p class="nav-link disabled">Step 2</p>
            </li>
            <li class="nav-item">
              <p class="nav-link disabled">Step 3</p>
            </li>
            <li class="nav-item">
                <p class="nav-link disabled">Step 4</p>
            </li>
          </ul>
        </div>
      </div>
    <div class="select_airline">
    {% if airlines %}
    <div class="content">
    <h1>Select an Airline</h1>
    <ol class="list-group list-group-numbered">
        {% for airline in airlines %}
            {% set airline_code = airline_code(airline) %}   
            <li class="list-group-item">   
            <a href="{{ url_for('reservation.select_airline', 
            airline_code=airline_code, 
            base_code=base_code, 
            to_code=to_code, 
            fromAirport = fromAirport, 
            destinationAirport = destinationAirport, 
            departure = departure.isoformat(), 
            return_departure=return_departure.isoformat(), back=back )}}">{{ airline }}</a></li>
        {% endfor %}</ol>
    </div></div></div>
    {% else %}
    <div class="content">
    <h1>Sorry, we don't fly that direction</h1>
    <a href="/"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
      <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8"/>
    </svg>Back to search</a></div>
    {% endif %}</div>
{% endblock %}

templates/via.html
{% extends "base.html" %}

{% block title %}
Via Connections
{% endblock %}

{% block main %}
<div class="container">
    <h1>Sorry, you can only fly with one of flowing stop to chosen destination</h1>
    {% for connection in via %}
        <p>connection</p>
    {% endfor %}
        <a href="/search">Back to search</a>
</div>
{% endblock %}